FROM spikeinterface/tridesclous-base:1.6.3

# RUN pip install simplejson requests click
RUN pip install MEArec

RUN pip install --force --upgrade https://github.com/samuelgarcia/spikeinterface/archive/big_refactoring.zip

RUN pip install --force --upgrade https://github.com/NeuralEnsemble/python-neo/archive/master.zip

# when release then
# RUN pip install spikeinterface>=0.90
#
