FROM spikeinterface/herdingspikes-base:0.3.7

RUN pip install simplejson requests click

#########################################
### SpikeInterface
RUN pip install spikeextractors==0.9.6 spiketoolkit==0.7.5 spikesorters==0.4.4

### Install extractors
RUN pip install h5py
RUN pip install scipy
RUN pip install pyintan
RUN pip install pyopenephys
RUN pip install neo
RUN pip install MEArec
RUN pip install pynwb
RUN pip install lxml
RUN pip install nixio
RUN pip install shybrid pyyaml
RUN pip install mtscomp
RUN pip install sonpy