FROM nvidia/cuda:10.0-base-ubuntu18.04 

LABEL maintainer="Vincent Prevosto <prevosto@mit.edu>"

# Copy files for dev/tests
COPY packages /srv/packages
COPY test_files /home/test_files

# USER root
# Ubuntu package installs
RUN apt update && \
    apt install -y --no-install-recommends \
    libfftw3-dev \
    git \
    wget && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# install miniconda
ENV MINICONDA_VERSION 4.12.0
ENV CONDA_DIR /home/miniconda3
ENV LATEST_CONDA_SCRIPT "Miniconda3-py38_$MINICONDA_VERSION-Linux-x86_64.sh"

RUN wget --quiet https://repo.anaconda.com/miniconda/$LATEST_CONDA_SCRIPT -O ~/miniconda.sh && \
    bash ~/miniconda.sh -b -p $CONDA_DIR && \
    rm ~/miniconda.sh
# RUN echo 'export PATH="/home/miniconda3/bin:$PATH"' >> ~/.bashrc 
ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda update conda && \
    conda install conda-build

# make conda activate command available from /bin/bash --login shells
RUN echo ". $CONDA_DIR/etc/profile.d/conda.sh" >> /root/.profile 
# make conda activate command available from /bin/bash --interactive shells
RUN conda init bash

# Install IBL port of pykilosort
RUN git clone -b drift_test_stable https://github.com/kushbanga/pykilosort.git /src/pykilosort
WORKDIR /src/pykilosort

# Create environment
RUN conda env create -f pyks2.yml

# Install pykilosort
SHELL ["conda","run","-n","pyks2","/bin/bash","-c"]
RUN conda install --quiet --yes ipykernel && \
    python -m ipykernel install --user --name pyks2 --display-name "pyKilosort" && \
    pip install -U -r /srv/packages/testing_requirements.txt && \
    conda develop .   

RUN rm -rf /srv/packages
