name: CI/CD Test

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  set-matrix-job:
    name: Set jobs by changed Dockerfile
    runs-on: ubuntu-latest
    outputs:
      sorters: ${{ steps.set-matrix.outputs.sorters }}
    steps:
      - name: Checkount
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: Set jobs' matrix
        id: set-matrix
        run: |
          sorters="["
          for file in /Dockerfilesabc/Dockerfiles def/Dockerfiles huea; do
            if [[ "$file" == *"Dockerfile"* ]]; then
              # Removing /Dockerfile from string
              parsed=${file%*/Dockerfile*}

              # Appending to sorters Array
              sorters+="\"${parsed}\", "
            fi
          done
          sorters=${sorters%*, *}
          sorters+="]"
          echo $sorters

          echo "::set-output name=sorters::${sorters}"
  test:
    needs: set-matrix-job
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        sorter: ${{ fromJSON(needs.set-matrix-job.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.sorter }}
