name: Full spikeinterface tests

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.8
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git 

          # get SI form master
          git clone https://github.com/SpikeInterface/spikeinterface.git
          cd spikeinterface
          pip install .
          pip install -r requirements_full.txt

          cd ..
          pip install spython pytest
      - name: Test singularity
        run: |
          pytest -v tests/test_singularity_containers.py
