name: Test sorter images in singularity

on:
  push:
    branches: [add_ci_tests]

jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: 3.8
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install git 

          pip install -r requirements_test.txt
      - name: Test tridesclous image
        run: |
          pip install tridesclous
          pytest -sv tests/test_singularity_containers.py::test_tridesclous
      - name: Test spyking-circus image
        run: pytest -sv tests/test_singularity_containers.py::test_spyking_circus
