name: Test sorter images in singularity

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  test-images:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # "macos-latest", "windows-latest"
        os: ["ubuntu-latest", ]
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: 3.8

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Install dependencies
        run: |
          pip install tridesclous
          pip install -r requirements_test.txt

      - name: Run test singularity containers
        run: |
          pip install tridesclous
          pytest -sv tests/test_singularity_containers.py
